[commitizen]
changelog_file = "CHANGELOG.md"
tag_format = "v$major.$minor.$patch$prerelease"
update_changelog_on_bump = true
version = "0.0.0"
version_files = ["setup.py:version", "src/__init__.py:__version__"]